export interface Palette {
  id: number;
  name: string;
  category: string;
  colors: {
    bg: string;
    bgAlt: string;
    card: string;
    accent: string;
    accentLight: string;
    accentDark: string;
    text: string;
    textSecondary: string;
    button: string;
    buttonText: string;
  };
}

export const palettes: Palette[] = [
  // Категория: ТЁПЛЫЙ БЕЖ (1-10)
  {
    id: 1,
    name: "Песочная дюна",
    category: "Тёплый беж",
    colors: {
      bg: "#E8DDD4",
      bgAlt: "#DED2C8",
      card: "#F5EDE6",
      accent: "#C4A484",
      accentLight: "#E5D9CA",
      accentDark: "#9A7B5A",
      text: "#5D4E3C",
      textSecondary: "#7D6E5C",
      button: "#B8956E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 2,
    name: "Ванильный латте",
    category: "Тёплый беж",
    colors: {
      bg: "#F0E6D8",
      bgAlt: "#E6DCCE",
      card: "#FAF5ED",
      accent: "#D4A574",
      accentLight: "#EBD9C4",
      accentDark: "#AA7B4A",
      text: "#6B5344",
      textSecondary: "#8B7364",
      button: "#C69C6D",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 3,
    name: "Сахарный тростник",
    category: "Тёплый беж",
    colors: {
      bg: "#EDE4D3",
      bgAlt: "#E3DAC9",
      card: "#F8F3EA",
      accent: "#CAAA7E",
      accentLight: "#E8DCCA",
      accentDark: "#A08054",
      text: "#5A4A38",
      textSecondary: "#7A6A58",
      button: "#BFA068",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 4,
    name: "Миндальное молоко",
    category: "Тёплый беж",
    colors: {
      bg: "#EFE6DB",
      bgAlt: "#E5DCD1",
      card: "#F9F4ED",
      accent: "#C8A882",
      accentLight: "#E6D8C6",
      accentDark: "#9E7E58",
      text: "#5E4D3D",
      textSecondary: "#7E6D5D",
      button: "#BA9A6C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 5,
    name: "Овсяное печенье",
    category: "Тёплый беж",
    colors: {
      bg: "#E6DCD0",
      bgAlt: "#DCD2C6",
      card: "#F4EDE4",
      accent: "#C2A07A",
      accentLight: "#E2D4C2",
      accentDark: "#987650",
      text: "#594839",
      textSecondary: "#796859",
      button: "#B49468",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 6,
    name: "Слоновая кость",
    category: "Тёплый беж",
    colors: {
      bg: "#F2E8DC",
      bgAlt: "#E8DED2",
      card: "#FAF6F0",
      accent: "#D0B08C",
      accentLight: "#EADcCC",
      accentDark: "#A68662",
      text: "#605040",
      textSecondary: "#807060",
      button: "#C4A276",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 7,
    name: "Пшеничное поле",
    category: "Тёплый беж",
    colors: {
      bg: "#E9DFCF",
      bgAlt: "#DFD5C5",
      card: "#F5EFE4",
      accent: "#CCA86E",
      accentLight: "#E6D8BE",
      accentDark: "#A27E44",
      text: "#584834",
      textSecondary: "#786854",
      button: "#BE9A5E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 8,
    name: "Кашемир",
    category: "Тёплый беж",
    colors: {
      bg: "#EBE2D6",
      bgAlt: "#E1D8CC",
      card: "#F6F0E8",
      accent: "#C6A888",
      accentLight: "#E4D6C4",
      accentDark: "#9C7E5E",
      text: "#5C4C3E",
      textSecondary: "#7C6C5E",
      button: "#B89A72",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 9,
    name: "Крем-брюле",
    category: "Тёплый беж",
    colors: {
      bg: "#F0E4D4",
      bgAlt: "#E6DACA",
      card: "#F9F3E8",
      accent: "#D4AA70",
      accentLight: "#ECDCC0",
      accentDark: "#AA8046",
      text: "#5E4A36",
      textSecondary: "#7E6A56",
      button: "#C89C5A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 10,
    name: "Античный белый",
    category: "Тёплый беж",
    colors: {
      bg: "#EDE5D8",
      bgAlt: "#E3DBCE",
      card: "#F7F1E8",
      accent: "#C8A47C",
      accentLight: "#E6D6C0",
      accentDark: "#9E7A52",
      text: "#5B4B3B",
      textSecondary: "#7B6B5B",
      button: "#BA9666",
      buttonText: "#FFFFFF",
    },
  },

  // Категория: ПЕРСИК И АБРИКОС (11-20)
  {
    id: 11,
    name: "Спелый персик",
    category: "Персик и абрикос",
    colors: {
      bg: "#F5E0D4",
      bgAlt: "#EBD6CA",
      card: "#FBF0E8",
      accent: "#E8A882",
      accentLight: "#F5D4C0",
      accentDark: "#BE7E58",
      text: "#6B4D42",
      textSecondary: "#8B6D62",
      button: "#DA9670",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 12,
    name: "Персиковый сорбет",
    category: "Персик и абрикос",
    colors: {
      bg: "#F8E4D8",
      bgAlt: "#EEDACE",
      card: "#FDF2EB",
      accent: "#E4A078",
      accentLight: "#F4D0BA",
      accentDark: "#BA764E",
      text: "#684A3E",
      textSecondary: "#886A5E",
      button: "#D69066",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 13,
    name: "Абрикосовый джем",
    category: "Персик и абрикос",
    colors: {
      bg: "#F4DDD0",
      bgAlt: "#EAD3C6",
      card: "#FAEDE4",
      accent: "#E09A72",
      accentLight: "#F2CCB4",
      accentDark: "#B67048",
      text: "#664840",
      textSecondary: "#866860",
      button: "#D28A60",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 14,
    name: "Коралловый песок",
    category: "Персик и абрикос",
    colors: {
      bg: "#F2DCD2",
      bgAlt: "#E8D2C8",
      card: "#F9EBE4",
      accent: "#DC9878",
      accentLight: "#F0CAB2",
      accentDark: "#B26E4E",
      text: "#644640",
      textSecondary: "#846660",
      button: "#CE8868",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 15,
    name: "Румяна",
    category: "Персик и абрикос",
    colors: {
      bg: "#F6E2D6",
      bgAlt: "#ECD8CC",
      card: "#FCF0E8",
      accent: "#E4A080",
      accentLight: "#F4D2BC",
      accentDark: "#BA7656",
      text: "#6A4C42",
      textSecondary: "#8A6C62",
      button: "#D6906E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 16,
    name: "Дыня",
    category: "Персик и абрикос",
    colors: {
      bg: "#F4E0D0",
      bgAlt: "#EAD6C6",
      card: "#FAEEE4",
      accent: "#E2A272",
      accentLight: "#F2D0B0",
      accentDark: "#B87848",
      text: "#664A3C",
      textSecondary: "#866A5C",
      button: "#D49262",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 17,
    name: "Пастельный апельсин",
    category: "Персик и абрикос",
    colors: {
      bg: "#F8E2D2",
      bgAlt: "#EED8C8",
      card: "#FDF0E6",
      accent: "#E8A46C",
      accentLight: "#F6D2AA",
      accentDark: "#BE7A42",
      text: "#6A4C38",
      textSecondary: "#8A6C58",
      button: "#DA945C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 18,
    name: "Лососевый мусс",
    category: "Персик и абрикос",
    colors: {
      bg: "#F2DED4",
      bgAlt: "#E8D4CA",
      card: "#F9ECE6",
      accent: "#DC9C7A",
      accentLight: "#F0CCB6",
      accentDark: "#B27250",
      text: "#64483E",
      textSecondary: "#84685E",
      button: "#CE8C6A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 19,
    name: "Шампанское",
    category: "Персик и абрикос",
    colors: {
      bg: "#F5E4D6",
      bgAlt: "#EBDACC",
      card: "#FBF1E8",
      accent: "#E0A67E",
      accentLight: "#F2D2BA",
      accentDark: "#B67C54",
      text: "#684E40",
      textSecondary: "#886E60",
      button: "#D29668",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 20,
    name: "Фламинго",
    category: "Персик и абрикос",
    colors: {
      bg: "#F4DED6",
      bgAlt: "#EAD4CC",
      card: "#FAECE6",
      accent: "#DE9C80",
      accentLight: "#F0CEBA",
      accentDark: "#B47256",
      text: "#664844",
      textSecondary: "#866864",
      button: "#D08C70",
      buttonText: "#FFFFFF",
    },
  },

  // Категория: ТЕРРАКОТА И ГЛИНА (21-30)
  {
    id: 21,
    name: "Тосканская глина",
    category: "Терракота и глина",
    colors: {
      bg: "#E8D8CC",
      bgAlt: "#DECEC2",
      card: "#F4EAE0",
      accent: "#C49474",
      accentLight: "#E2C8B0",
      accentDark: "#9A6A4A",
      text: "#5A4638",
      textSecondary: "#7A6658",
      button: "#B68464",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 22,
    name: "Песчаник",
    category: "Терракота и глина",
    colors: {
      bg: "#E6D6C8",
      bgAlt: "#DCCCBE",
      card: "#F2E8DC",
      accent: "#C09070",
      accentLight: "#DEC4AA",
      accentDark: "#966646",
      text: "#584436",
      textSecondary: "#786456",
      button: "#B28060",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 23,
    name: "Марокканская пустыня",
    category: "Терракота и глина",
    colors: {
      bg: "#E4D4C4",
      bgAlt: "#DACABA",
      card: "#F0E6DA",
      accent: "#BC8C6C",
      accentLight: "#DAC0A4",
      accentDark: "#926242",
      text: "#564234",
      textSecondary: "#766254",
      button: "#AE7C5C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 24,
    name: "Глиняный горшок",
    category: "Терракота и глина",
    colors: {
      bg: "#E2D2C2",
      bgAlt: "#D8C8B8",
      card: "#EEE4D6",
      accent: "#B88868",
      accentLight: "#D6BC9E",
      accentDark: "#8E5E3E",
      text: "#544032",
      textSecondary: "#746052",
      button: "#AA7858",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 25,
    name: "Сафари",
    category: "Терракота и глина",
    colors: {
      bg: "#E6D8C6",
      bgAlt: "#DCCEBC",
      card: "#F2EAD8",
      accent: "#C49470",
      accentLight: "#E0C8A8",
      accentDark: "#9A6A46",
      text: "#584634",
      textSecondary: "#786654",
      button: "#B68460",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 26,
    name: "Каньон",
    category: "Терракота и глина",
    colors: {
      bg: "#E4D4C0",
      bgAlt: "#DACAB6",
      card: "#F0E6D4",
      accent: "#C0906A",
      accentLight: "#DCC4A0",
      accentDark: "#966640",
      text: "#564230",
      textSecondary: "#766250",
      button: "#B2805A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 27,
    name: "Египетский песок",
    category: "Терракота и глина",
    colors: {
      bg: "#E8DAC8",
      bgAlt: "#DED0BE",
      card: "#F4ECDC",
      accent: "#C8986E",
      accentLight: "#E2CCA4",
      accentDark: "#9E6E44",
      text: "#5A4834",
      textSecondary: "#7A6854",
      button: "#BA885E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 28,
    name: "Терракотовая крыша",
    category: "Терракота и глина",
    colors: {
      bg: "#E2D0C0",
      bgAlt: "#D8C6B6",
      card: "#EEE2D4",
      accent: "#B88664",
      accentLight: "#D4B898",
      accentDark: "#8E5C3A",
      text: "#524030",
      textSecondary: "#726050",
      button: "#AA7654",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 29,
    name: "Пустынная роза",
    category: "Терракота и глина",
    colors: {
      bg: "#E6D6C6",
      bgAlt: "#DCCCBC",
      card: "#F2E8DA",
      accent: "#C29272",
      accentLight: "#DEC4A8",
      accentDark: "#986848",
      text: "#584436",
      textSecondary: "#786456",
      button: "#B48262",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 30,
    name: "Каменная стена",
    category: "Терракота и глина",
    colors: {
      bg: "#E0D0C2",
      bgAlt: "#D6C6B8",
      card: "#ECE2D6",
      accent: "#B48462",
      accentLight: "#D2B696",
      accentDark: "#8A5A38",
      text: "#504030",
      textSecondary: "#706050",
      button: "#A67452",
      buttonText: "#FFFFFF",
    },
  },

  // Категория: КАРАМЕЛЬ И МЁД (31-40)
  {
    id: 31,
    name: "Жидкая карамель",
    category: "Карамель и мёд",
    colors: {
      bg: "#F0E0CC",
      bgAlt: "#E6D6C2",
      card: "#F8EEE0",
      accent: "#D4A060",
      accentLight: "#ECD090",
      accentDark: "#AA7636",
      text: "#5E4830",
      textSecondary: "#7E6850",
      button: "#C69050",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 32,
    name: "Липовый мёд",
    category: "Карамель и мёд",
    colors: {
      bg: "#EEE0C8",
      bgAlt: "#E4D6BE",
      card: "#F6ECDA",
      accent: "#D09C5C",
      accentLight: "#E8CC8C",
      accentDark: "#A67232",
      text: "#5C4630",
      textSecondary: "#7C6650",
      button: "#C28C4C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 33,
    name: "Золотой сироп",
    category: "Карамель и мёд",
    colors: {
      bg: "#F2E2CC",
      bgAlt: "#E8D8C2",
      card: "#F9EFE0",
      accent: "#D8A45E",
      accentLight: "#F0D48E",
      accentDark: "#AE7A34",
      text: "#604A30",
      textSecondary: "#806A50",
      button: "#CA9450",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 34,
    name: "Имбирное печенье",
    category: "Карамель и мёд",
    colors: {
      bg: "#EAD8C4",
      bgAlt: "#E0CEBA",
      card: "#F4E8D8",
      accent: "#C8945C",
      accentLight: "#E4C68C",
      accentDark: "#9E6A32",
      text: "#584230",
      textSecondary: "#786250",
      button: "#BA8450",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 35,
    name: "Тоффи",
    category: "Карамель и мёд",
    colors: {
      bg: "#ECDCC8",
      bgAlt: "#E2D2BE",
      card: "#F5EADC",
      accent: "#CC9858",
      accentLight: "#E6CA88",
      accentDark: "#A26E2E",
      text: "#5A4430",
      textSecondary: "#7A6450",
      button: "#BE884A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 36,
    name: "Арахисовое масло",
    category: "Карамель и мёд",
    colors: {
      bg: "#E8D8C2",
      bgAlt: "#DECEB8",
      card: "#F2E6D6",
      accent: "#C49258",
      accentLight: "#E0C484",
      accentDark: "#9A682E",
      text: "#564030",
      textSecondary: "#766050",
      button: "#B68248",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 37,
    name: "Банановый хлеб",
    category: "Карамель и мёд",
    colors: {
      bg: "#EEE0CA",
      bgAlt: "#E4D6C0",
      card: "#F6ECDC",
      accent: "#D09A54",
      accentLight: "#EACC82",
      accentDark: "#A6702A",
      text: "#5C4630",
      textSecondary: "#7C6650",
      button: "#C28A44",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 38,
    name: "Засахаренный имбирь",
    category: "Карамель и мёд",
    colors: {
      bg: "#ECDAC6",
      bgAlt: "#E2D0BC",
      card: "#F5E8D8",
      accent: "#CA9654",
      accentLight: "#E6C882",
      accentDark: "#A06C2A",
      text: "#584230",
      textSecondary: "#786250",
      button: "#BC8646",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 39,
    name: "Овсяный мёд",
    category: "Карамель и мёд",
    colors: {
      bg: "#E8DCC6",
      bgAlt: "#DED2BC",
      card: "#F4E8D8",
      accent: "#C69656",
      accentLight: "#E2C684",
      accentDark: "#9C6C2C",
      text: "#564230",
      textSecondary: "#766250",
      button: "#B88648",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 40,
    name: "Дульсе де лече",
    category: "Карамель и мёд",
    colors: {
      bg: "#EADAC4",
      bgAlt: "#E0D0BA",
      card: "#F4E8D6",
      accent: "#C8945A",
      accentLight: "#E4C688",
      accentDark: "#9E6A30",
      text: "#584230",
      textSecondary: "#786250",
      button: "#BA844C",
      buttonText: "#FFFFFF",
    },
  },

  // Категория: ПУДРОВЫЙ ОРАНЖ (41-50)
  {
    id: 41,
    name: "Оранжевый крем",
    category: "Пудровый оранж",
    colors: {
      bg: "#F6E4D0",
      bgAlt: "#ECDAC6",
      card: "#FCF0E4",
      accent: "#E8A060",
      accentLight: "#F4CC90",
      accentDark: "#BE7636",
      text: "#6A4C34",
      textSecondary: "#8A6C54",
      button: "#DA9050",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 42,
    name: "Тыквенный латте",
    category: "Пудровый оранж",
    colors: {
      bg: "#F4E0CC",
      bgAlt: "#EAD6C2",
      card: "#FAEEE0",
      accent: "#E49C5C",
      accentLight: "#F2C88A",
      accentDark: "#BA7232",
      text: "#684A32",
      textSecondary: "#886A52",
      button: "#D68C4C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 43,
    name: "Закатное небо",
    category: "Пудровый оранж",
    colors: {
      bg: "#F8E4D2",
      bgAlt: "#EEDAC8",
      card: "#FDF0E6",
      accent: "#EAA464",
      accentLight: "#F6D094",
      accentDark: "#C07A3A",
      text: "#6C4E36",
      textSecondary: "#8C6E56",
      button: "#DC9454",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 44,
    name: "Мандариновый сорбет",
    category: "Пудровый оранж",
    colors: {
      bg: "#F6E2D0",
      bgAlt: "#ECD8C6",
      card: "#FCEFE4",
      accent: "#E6A05E",
      accentLight: "#F4CC8E",
      accentDark: "#BC7634",
      text: "#6A4C34",
      textSecondary: "#8A6C54",
      button: "#D8904E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 45,
    name: "Осенний лист",
    category: "Пудровый оранж",
    colors: {
      bg: "#F0DCC8",
      bgAlt: "#E6D2BE",
      card: "#F8EADC",
      accent: "#DC985A",
      accentLight: "#F0C488",
      accentDark: "#B26E30",
      text: "#644830",
      textSecondary: "#846850",
      button: "#CE884A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 46,
    name: "Медный блеск",
    category: "Пудровый оранж",
    colors: {
      bg: "#EED8C4",
      bgAlt: "#E4CEBA",
      card: "#F6E6D6",
      accent: "#D49456",
      accentLight: "#ECC082",
      accentDark: "#AA6A2C",
      text: "#604630",
      textSecondary: "#806650",
      button: "#C68446",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 47,
    name: "Облепиховый чай",
    category: "Пудровый оранж",
    colors: {
      bg: "#F4E0CA",
      bgAlt: "#EAD6C0",
      card: "#FAEDE0",
      accent: "#E09A56",
      accentLight: "#F2C684",
      accentDark: "#B6702C",
      text: "#664A30",
      textSecondary: "#866A50",
      button: "#D28A46",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 48,
    name: "Абрикосовый нектар",
    category: "Пудровый оранж",
    colors: {
      bg: "#F2DEC8",
      bgAlt: "#E8D4BE",
      card: "#F8EBDC",
      accent: "#DC9654",
      accentLight: "#F0C280",
      accentDark: "#B26C2A",
      text: "#644830",
      textSecondary: "#846850",
      button: "#CE8644",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 49,
    name: "Янтарная смола",
    category: "Пудровый оранж",
    colors: {
      bg: "#EED6C0",
      bgAlt: "#E4CCB6",
      card: "#F6E4D4",
      accent: "#D49250",
      accentLight: "#ECBE7C",
      accentDark: "#AA6826",
      text: "#5E4430",
      textSecondary: "#7E6450",
      button: "#C68240",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 50,
    name: "Золотой час",
    category: "Пудровый оранж",
    colors: {
      bg: "#F0DCC6",
      bgAlt: "#E6D2BC",
      card: "#F8EAD8",
      accent: "#D8985A",
      accentLight: "#EEC486",
      accentDark: "#AE6E30",
      text: "#624830",
      textSecondary: "#826850",
      button: "#CA8848",
      buttonText: "#FFFFFF",
    },
  },
];

export const paletteCategories = [
  "Тёплый беж",
  "Персик и абрикос",
  "Терракота и глина",
  "Карамель и мёд",
  "Пудровый оранж",
];

export function getPaletteById(id: number): Palette | undefined {
  return palettes.find((p) => p.id === id);
}

export function getPalettesByCategory(category: string): Palette[] {
  return palettes.filter((p) => p.category === category);
}
